spring:
  application:
    name: cart

#  security:
#    oauth2:
#      resourceserver:
#        jwt:
#          jwk-set-uri: http://localhost:9000/realms/clownstore/protocol/openid-connect/certs

  data:
    redis:
      host: localhost
      port: 6379
server:
  port: 8081

product:
  service:
    url: http://localhost:8080